id: I8861CDB6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T06:01:33+00:00'
last_modified: '2022-06-08T06:08:56.509731+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3026
  title: སྔ་འགྱུར་རྙིང་མའི་གླེགས་བམ་རིན་པོ་ཆེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E1B5:
      image_group_id: I3CN3158
      title: ''
      total_pages: 542
      order: 1
      base_file: E1B5.txt
    857F:
      image_group_id: I3CN3159
      title: ''
      total_pages: 598
      order: 2
      base_file: 857F.txt
    F912:
      image_group_id: I3CN3160
      title: ''
      total_pages: 568
      order: 3
      base_file: F912.txt
    878D:
      image_group_id: I3CN3161
      title: ''
      total_pages: 426
      order: 4
      base_file: 878D.txt
    ECD4:
      image_group_id: I3CN3162
      title: ''
      total_pages: 636
      order: 5
      base_file: ECD4.txt
    08E6:
      image_group_id: I3CN3163
      title: ''
      total_pages: 550
      order: 6
      base_file: 08E6.txt
    '5170':
      image_group_id: I3CN3164
      title: ''
      total_pages: 582
      order: 7
      base_file: 5170.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
