id: I8861CDB6
legacy_id: P006687
ocr_import_info:
  bdrc_scan_id: W3CN3026
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T05:56:41'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T13:15:03.851353+00:00'
last_modified: 2022-09-03 21:17:09.805076
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN3026
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN3026
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྔ་འགྱུར་རྙིང་མའི་གླེགས་བམ་རིན་པོ་ཆེ།
statistics:
  ocr_word_mean_confidence_index: 0.9592399683193101
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I3CN3160:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3160
      total_pages: 568
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3CN3160.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9612804194536574
    legacy_id: v003
  I3CN3161:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3161
      total_pages: 426
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3CN3161.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.959808249089043
    legacy_id: v004
  I3CN3158:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3158
      total_pages: 542
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN3158.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9531582007010269
    legacy_id: v001
  I3CN3163:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3163
      total_pages: 550
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I3CN3163.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9609755149834315
    legacy_id: v006
  I3CN3162:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3162
      total_pages: 636
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3CN3162.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9589307766564714
    legacy_id: v005
  I3CN3159:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3159
      total_pages: 598
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN3159.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9561153774772936
    legacy_id: v002
  I3CN3164:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3164
      total_pages: 582
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I3CN3164.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9633640337431281
    legacy_id: v007
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
